services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: go-images-rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - images
  producer:
    build: ./mock-producer
    ports:
      - "2137:2137"
    networks:
      - images
    environment:
      - RABBIT_ADDR=rabbitmq

networks:
  images:
